### ISSUE TITLE
Config not changing colors as intended

### ISSUE THREAD

**Issue by sylodani** [nettyneets/apex-n#3]
Basically, the title says it all, but I've changed a nice bit in the config menu like enabling class colors time/heaviest hit colors and they aren't changing even after I restart ACT

**Comment by nyliya** [comment]
_This has been tested on 4 different computers by 3 different users. The config changed colors in all 4 cases and this cannot be replicated._

1. Are you using version 1.3 or later? Downloaded from [releases](https://github.com/nettyneets/apex-n/releases) and not via Download as zip on the main page.
2. How are you editing the config? You cannot edit it directly in the ACT folder. Copy it onto your desktop, make your changes and then paste it back into ACT.
3. Can you verify the existence of 3 .js files in /Build/resources/js/apex-n, one of them being apex-n-css.js?
4. Can you please provide me with a copy of your config using [pastebin](https://pastebin.com/).

**Comment by sylodani** [comment]
1. I am using version 1.4 as of right now. 

2. I have also done that. I've never had ACT open either while I've edited apex-n-config.

3. Here are the three files with location

![](https://i.gyazo.com/720489eede1f293e054ba684942ea4e2.png)

4. Here is the pastebin of my apex-n-config 

https://pastebin.com/qcPi6jpk

I apologize I took so long to get back to you. It's only the aesthetics that aren't working so it's not top priority or anything. I don't know why it seems to be an isolated case either unless you find something wrong with what I sent you. Once again, sorry about taking so long to get back to you and hope you can figure out what's up.

**Comment by nyliya** [comment]
Your config seems fine, however I noticed the path on your screenshot is incorrect.
You have a folder inside of a folder? This will result in the path from the main html being incorrect.
![YourPath](https://user-images.githubusercontent.com/7468340/30589719-8ae44d0c-9d33-11e7-87ee-6abeca08e565.png)

This is what the path should look like
![CorrectPath](https://user-images.githubusercontent.com/7468340/30589782-c0fd30c0-9d33-11e7-9525-75a85f644f2d.png)

The html files should be in `Advanced Combat Tracker/Build/resources` with no subfolders

The js files should be in `Advanced Combat Tracker/Build/resources/js` in an "apex-n" subfolder

The css  should be in `Advanced Combat Tracker/Build/resources/css` in an "apex-n" subfolder

This should resolve your issue! 👍
