### ISSUE TITLE
Overlay not refreshing (occurs mostly during dungeons)

### ISSUE THREAD

**Issue by aimoaio** [nettyneets/apex-n#5]
![image](https://user-images.githubusercontent.com/5750927/30783597-71b75fbe-a13d-11e7-92e2-be0388fe614e.png)

Hi, 

I'm receiving an UncaughtTypeError and NullReferenceException in the log causing the mini overlay to not refresh during encounters - it usually ends up parsing and then being stuck at a certain duration (eg. 22s) while ACT is still parsing correctly.

This tends to only happen in dungeons when the encounter isn't reset between pulls (as I've noticed no issues during raid). Instead of receiving an overall parse as the encounter goes on, the overlay is usually stuck after the first pull. However once the dungeon ends, it displays the correct numbers.

I tested with another overlay (https://hibiyasleep.github.io/kagerou/overlay/) and received no exceptions and was able to get an accurate encounter parse.

![image](https://user-images.githubusercontent.com/5750927/30783665-bc619484-a13e-11e7-870a-0a6403112018.png)

Currently using the latest version from your Github page. Not sure if I'm missing something here?

**Comment by nyliya** [comment]
This has not happened to me so far, but I don't do many dungeons mainly just raids which might explain why that's the case. I will try to replicate this issue and come up with a fix. Thanks for bringing this to my attention!
